// Auto-generated from my_data_sets/daily_food_nutrition_dataset.csv by scripts/generate-food-seed-data.mjs.
// Deduped by name (593 unique of 651 rows; the rest were exact
// repeats). Regenerate rather than hand-edit.
export type SeedFood = {
  name: string
  category: string
  calories: number
  proteinG: number
  carbsG: number
  fatG: number
  fiberG: number
}

export const SEED_FOODS: SeedFood[] = [
  { name: "Acai Bowl (1 serving)", category: "Meal/Fruit", calories: 350, proteinG: 5, carbsG: 60, fatG: 12, fiberG: 10 },
  { name: "Aioli (Garlic 1 tbsp)", category: "Condiment", calories: 95, proteinG: 0.1, carbsG: 0.5, fatG: 10.5, fiberG: 0 },
  { name: "Aji Amarillo Paste (1 tsp)", category: "Condiment", calories: 5, proteinG: 0.1, carbsG: 1, fatG: 0, fiberG: 0.5 },
  { name: "Alfajores (1 cookie)", category: "Dessert", calories: 180, proteinG: 2, carbsG: 22, fatG: 10, fiberG: 1 },
  { name: "Almond Milk (Unsweetened 1 cup)", category: "Beverage/Dairy-Alt", calories: 30, proteinG: 1, carbsG: 1, fatG: 2.5, fiberG: 1 },
  { name: "Almonds (1 oz)", category: "Nut", calories: 164, proteinG: 6, carbsG: 6, fatG: 14, fiberG: 3.5 },
  { name: "Amaretti Cookie (2 cookies)", category: "Dessert", calories: 90, proteinG: 2, carbsG: 12, fatG: 4, fiberG: 1 },
  { name: "Angel Hair Pasta (1 cup)", category: "Grain", calories: 200, proteinG: 7, carbsG: 42, fatG: 1, fiberG: 2 },
  { name: "Angostura Bitters (dash)", category: "Condiment", calories: 5, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Ants on a Log (4 pcs)", category: "Snack", calories: 180, proteinG: 6, carbsG: 12, fatG: 12, fiberG: 3 },
  { name: "Aperol Spritz (1 drink)", category: "Beverage", calories: 180, proteinG: 0, carbsG: 20, fatG: 0, fiberG: 0 },
  { name: "Apple", category: "Fruit", calories: 95, proteinG: 0.5, carbsG: 25, fatG: 0.3, fiberG: 4.4 },
  { name: "Apple Cider (1 cup)", category: "Beverage", calories: 117, proteinG: 0.1, carbsG: 29, fatG: 0.3, fiberG: 0.5 },
  { name: "Apple Pie (1 slice)", category: "Dessert", calories: 410, proteinG: 3, carbsG: 58, fatG: 19, fiberG: 3 },
  { name: "Arancini (1 large ball)", category: "Snack/Processed", calories: 250, proteinG: 9, carbsG: 30, fatG: 10, fiberG: 3 },
  { name: "Artichoke (1 medium steamed)", category: "Vegetable", calories: 60, proteinG: 4.2, carbsG: 13.4, fatG: 0.2, fiberG: 6.9 },
  { name: "Arugula (2 cups)", category: "Vegetable", calories: 10, proteinG: 1, carbsG: 0.8, fatG: 0.2, fiberG: 0.4 },
  { name: "Asparagus (1 cup steamed)", category: "Vegetable", calories: 40, proteinG: 4.3, carbsG: 7.4, fatG: 0.4, fiberG: 3.6 },
  { name: "Asparagus (6 spears roasted)", category: "Vegetable", calories: 40, proteinG: 4, carbsG: 4, fatG: 2, fiberG: 3 },
  { name: "Avocado (1/2 fruit)", category: "Fruit", calories: 160, proteinG: 2, carbsG: 8.5, fatG: 14.7, fiberG: 6.7 },
  { name: "Avocado Toast (1 slice)", category: "Meal/Vegetarian", calories: 260, proteinG: 7, carbsG: 28, fatG: 15, fiberG: 10 },
  { name: "Baba Ganoush (1/4 cup)", category: "Meal/Vegetable", calories: 100, proteinG: 2, carbsG: 8, fatG: 7, fiberG: 4 },
  { name: "Bacon (2 slices cooked)", category: "Protein/Meat", calories: 86, proteinG: 6, carbsG: 0.2, fatG: 6.8, fiberG: 0 },
  { name: "Bagel (plain)", category: "Grain", calories: 270, proteinG: 11, carbsG: 55, fatG: 1.5, fiberG: 2 },
  { name: "Baguette (slice)", category: "Grain", calories: 70, proteinG: 2.5, carbsG: 14, fatG: 0.5, fiberG: 0.6 },
  { name: "Baked Potato (medium)", category: "Vegetable", calories: 160, proteinG: 4.3, carbsG: 36, fatG: 0.2, fiberG: 3.8 },
  { name: "Baklava (1 piece)", category: "Dessert", calories: 280, proteinG: 3, carbsG: 30, fatG: 18, fiberG: 2 },
  { name: "Balsamic Glaze (1 tbsp)", category: "Condiment", calories: 40, proteinG: 0, carbsG: 9, fatG: 0, fiberG: 0 },
  { name: "Balsamic Glaze (1 tsp)", category: "Condiment", calories: 13, proteinG: 0, carbsG: 3, fatG: 0, fiberG: 0 },
  { name: "Balsamic Vinaigrette (2 tbsp)", category: "Condiment", calories: 90, proteinG: 0, carbsG: 3, fatG: 9, fiberG: 0 },
  { name: "Banana", category: "Fruit", calories: 105, proteinG: 1.3, carbsG: 27, fatG: 0.4, fiberG: 3.1 },
  { name: "Basil (2 tbsp fresh)", category: "Condiment", calories: 1, proteinG: 0.1, carbsG: 0.1, fatG: 0, fiberG: 0.1 },
  { name: "Basil (fresh garnish)", category: "Condiment", calories: 1, proteinG: 0.1, carbsG: 0, fatG: 0, fiberG: 0.1 },
  { name: "BBQ Sauce (2 tbsp)", category: "Condiment", calories: 60, proteinG: 0.5, carbsG: 15, fatG: 0, fiberG: 0.5 },
  { name: "Bean Sprouts (1/4 cup garnish)", category: "Vegetable", calories: 8, proteinG: 0.8, carbsG: 1.5, fatG: 0.1, fiberG: 0.4 },
  { name: "Beef Burrito (large)", category: "Meal/Processed", calories: 650, proteinG: 30, carbsG: 70, fatG: 28, fiberG: 10 },
  { name: "Beef Jerky (1 oz)", category: "Snack/Processed", calories: 116, proteinG: 9.4, carbsG: 3.1, fatG: 7.2, fiberG: 0.5 },
  { name: "Beef Pho (1 large bowl)", category: "Meal/Soup", calories: 450, proteinG: 30, carbsG: 55, fatG: 12, fiberG: 4 },
  { name: "Beef Steak (6oz sirloin)", category: "Protein/Meat", calories: 270, proteinG: 42, carbsG: 0, fatG: 10, fiberG: 0 },
  { name: "Beef Stroganoff (1.5 cups)", category: "Meal/Pasta", calories: 550, proteinG: 30, carbsG: 40, fatG: 28, fiberG: 4 },
  { name: "Beef Tacos (2 hard shell)", category: "Meal/Meat", calories: 380, proteinG: 18, carbsG: 28, fatG: 22, fiberG: 5 },
  { name: "Beef Wellington (1 slice)", category: "Meal/Meat", calories: 600, proteinG: 30, carbsG: 35, fatG: 38, fiberG: 4 },
  { name: "Beer (12 oz light)", category: "Beverage", calories: 103, proteinG: 0.9, carbsG: 5.8, fatG: 0, fiberG: 0 },
  { name: "Beets (1/2 cup roasted)", category: "Vegetable", calories: 30, proteinG: 0.8, carbsG: 6.8, fatG: 0.1, fiberG: 1.4 },
  { name: "Bell Pepper (1 medium red)", category: "Vegetable", calories: 31, proteinG: 1.2, carbsG: 6, fatG: 0.3, fiberG: 2.1 },
  { name: "Bell Peppers & Onions (sautéed)", category: "Vegetable", calories: 60, proteinG: 1.5, carbsG: 10, fatG: 2, fiberG: 3 },
  { name: "Berry Coulis (1 tbsp)", category: "Condiment", calories: 20, proteinG: 0, carbsG: 5, fatG: 0, fiberG: 0.5 },
  { name: "Biryani (Chicken 1.5 cups)", category: "Meal/Meat", calories: 520, proteinG: 28, carbsG: 60, fatG: 18, fiberG: 5 },
  { name: "Biscotti (1 cookie)", category: "Dessert", calories: 110, proteinG: 2, carbsG: 18, fatG: 4, fiberG: 1 },
  { name: "Biscuits and Gravy (1 serving)", category: "Meal/Processed", calories: 480, proteinG: 10, carbsG: 45, fatG: 28, fiberG: 2 },
  { name: "Bison Burger (1 patty)", category: "Protein/Meat", calories: 150, proteinG: 22, carbsG: 0, fatG: 7, fiberG: 0 },
  { name: "Black Beans (1/2 cup)", category: "Legume", calories: 114, proteinG: 7.6, carbsG: 20.4, fatG: 0.5, fiberG: 7.5 },
  { name: "Black Pepper (1 tsp)", category: "Condiment", calories: 6, proteinG: 0.2, carbsG: 1.5, fatG: 0.1, fiberG: 0.6 },
  { name: "Black Pepper (1/2 tsp)", category: "Condiment", calories: 3, proteinG: 0.1, carbsG: 0.7, fatG: 0, fiberG: 0.3 },
  { name: "Black Pepper (1/4 tsp)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.2, fatG: 0, fiberG: 0.1 },
  { name: "Blackberries (1 cup)", category: "Fruit", calories: 62, proteinG: 2, carbsG: 13.8, fatG: 0.7, fiberG: 7.6 },
  { name: "Blue Cheese (1 oz)", category: "Dairy", calories: 100, proteinG: 6, carbsG: 0.7, fatG: 8, fiberG: 0 },
  { name: "Blue Cheese Dressing (2 tbsp)", category: "Condiment", calories: 150, proteinG: 1, carbsG: 2, fatG: 16, fiberG: 0 },
  { name: "Blueberries (1/2 cup)", category: "Fruit", calories: 42, proteinG: 0.5, carbsG: 11, fatG: 0.2, fiberG: 1.8 },
  { name: "Bobotie (1 serving)", category: "Meal/Meat", calories: 450, proteinG: 25, carbsG: 30, fatG: 25, fiberG: 5 },
  { name: "Bok Choy (1 cup steamed)", category: "Vegetable", calories: 10, proteinG: 1.5, carbsG: 2, fatG: 0.1, fiberG: 1 },
  { name: "Bread Roll (hoagie)", category: "Grain", calories: 200, proteinG: 6, carbsG: 38, fatG: 2, fiberG: 2 },
  { name: "Breadcrumbs (coating)", category: "Grain", calories: 25, proteinG: 0.5, carbsG: 4, fatG: 0.5, fiberG: 0.5 },
  { name: "Breadstick (1 large)", category: "Grain", calories: 160, proteinG: 4, carbsG: 28, fatG: 3, fiberG: 1 },
  { name: "Brie Cheese (1 oz)", category: "Dairy", calories: 95, proteinG: 6, carbsG: 0.1, fatG: 7.9, fiberG: 0 },
  { name: "Brown Rice (1 cup cooked)", category: "Grain", calories: 215, proteinG: 5, carbsG: 45, fatG: 1.8, fiberG: 3.5 },
  { name: "Bruschetta (2 pcs)", category: "Snack/Appetizer", calories: 180, proteinG: 4, carbsG: 25, fatG: 7, fiberG: 3 },
  { name: "Bubble Tea (16 oz milk tea)", category: "Beverage", calories: 320, proteinG: 2, carbsG: 70, fatG: 4, fiberG: 1 },
  { name: "Bulgur (1 tbsp shell)", category: "Grain", calories: 15, proteinG: 0.5, carbsG: 3.4, fatG: 0, fiberG: 0.8 },
  { name: "Bulgur (1/4 cup in tabouli)", category: "Grain", calories: 76, proteinG: 2.7, carbsG: 16.8, fatG: 0.2, fiberG: 4.1 },
  { name: "Bun (hamburger)", category: "Grain", calories: 140, proteinG: 4, carbsG: 26, fatG: 2, fiberG: 1 },
  { name: "Burger (cheeseburger)", category: "Meal/Processed", calories: 550, proteinG: 30, carbsG: 40, fatG: 30, fiberG: 3 },
  { name: "Butter (1 tbsp)", category: "Condiment/Dairy", calories: 100, proteinG: 0.1, carbsG: 0, fatG: 11, fiberG: 0 },
  { name: "Cabbage Slaw (side)", category: "Vegetable", calories: 60, proteinG: 1, carbsG: 8, fatG: 3, fiberG: 2 },
  { name: "Cacio e Pepe (1.5 cups)", category: "Meal/Pasta", calories: 500, proteinG: 18, carbsG: 65, fatG: 19, fiberG: 4 },
  { name: "Caesar Salad (with chicken)", category: "Meal/Protein", calories: 470, proteinG: 30, carbsG: 15, fatG: 30, fiberG: 3 },
  { name: "Calamari (fried 3oz)", category: "Meal/Seafood", calories: 150, proteinG: 13, carbsG: 8, fatG: 7, fiberG: 1 },
  { name: "Campari (1 oz)", category: "Beverage", calories: 80, proteinG: 0, carbsG: 10, fatG: 0, fiberG: 0 },
  { name: "Campari & Soda (1 drink)", category: "Beverage", calories: 85, proteinG: 0, carbsG: 10, fatG: 0, fiberG: 0 },
  { name: "Canadian Bacon (2 slices)", category: "Protein/Meat", calories: 80, proteinG: 12, carbsG: 1, fatG: 3, fiberG: 0 },
  { name: "Candied Fruit (1 tbsp)", category: "Fruit", calories: 30, proteinG: 0, carbsG: 8, fatG: 0, fiberG: 0.5 },
  { name: "Cannellini Beans (1/2 cup in soup)", category: "Legume", calories: 105, proteinG: 7, carbsG: 20, fatG: 0.5, fiberG: 6 },
  { name: "Cannoli (1 medium)", category: "Dessert", calories: 240, proteinG: 5, carbsG: 25, fatG: 13, fiberG: 1 },
  { name: "Capers (1 tbsp)", category: "Condiment", calories: 2, proteinG: 0.2, carbsG: 0.4, fatG: 0.1, fiberG: 0.3 },
  { name: "Capers (garnish)", category: "Condiment", calories: 2, proteinG: 0.2, carbsG: 0.4, fatG: 0.1, fiberG: 0.3 },
  { name: "Caponata (1/2 cup)", category: "Meal/Vegetable", calories: 180, proteinG: 2, carbsG: 15, fatG: 14, fiberG: 5 },
  { name: "Caprese Salad", category: "Meal/Vegetable", calories: 240, proteinG: 10, carbsG: 8, fatG: 18, fiberG: 2 },
  { name: "Caramel Sauce (1 tbsp)", category: "Condiment", calories: 60, proteinG: 0, carbsG: 13, fatG: 1, fiberG: 0 },
  { name: "Carbonara (1.5 cups)", category: "Meal/Pasta", calories: 650, proteinG: 25, carbsG: 60, fatG: 35, fiberG: 4 },
  { name: "Cardamom (in coffee)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.2, fatG: 0, fiberG: 0.1 },
  { name: "Carrot (1/4 minced in sauce)", category: "Vegetable", calories: 10, proteinG: 0.2, carbsG: 2.4, fatG: 0.1, fiberG: 0.7 },
  { name: "Carrot Sticks (1 cup)", category: "Vegetable", calories: 52, proteinG: 1.2, carbsG: 12.3, fatG: 0.3, fiberG: 3.6 },
  { name: "Cashews (1 oz roasted)", category: "Nut", calories: 163, proteinG: 4.3, carbsG: 9.2, fatG: 13.1, fiberG: 0.9 },
  { name: "Celery (1 stalk)", category: "Vegetable", calories: 6, proteinG: 0.3, carbsG: 1.2, fatG: 0.1, fiberG: 0.6 },
  { name: "Celery (1/4 stalk minced)", category: "Vegetable", calories: 2, proteinG: 0.1, carbsG: 0.4, fatG: 0, fiberG: 0.2 },
  { name: "Celery Sticks (1 cup)", category: "Vegetable", calories: 14, proteinG: 0.6, carbsG: 3, fatG: 0.2, fiberG: 1.4 },
  { name: "Century Egg (1 egg)", category: "Protein", calories: 100, proteinG: 7, carbsG: 1, fatG: 7, fiberG: 0 },
  { name: "Cereal (Frosted Flakes 1 cup)", category: "Grain/Processed", calories: 130, proteinG: 2, carbsG: 31, fatG: 0, fiberG: 1 },
  { name: "Cereal Bar (Fruit)", category: "Snack/Processed", calories: 140, proteinG: 2, carbsG: 30, fatG: 3, fiberG: 1 },
  { name: "Ceviche (1 cup fish)", category: "Meal/Fish", calories: 180, proteinG: 25, carbsG: 15, fatG: 2, fiberG: 3 },
  { name: "Chai Latte (12 oz)", category: "Beverage", calories: 190, proteinG: 7, carbsG: 32, fatG: 4, fiberG: 1 },
  { name: "Cheddar Cheese (1 oz)", category: "Dairy", calories: 115, proteinG: 7, carbsG: 1, fatG: 9.5, fiberG: 0 },
  { name: "Cheese Danish", category: "Dessert", calories: 340, proteinG: 7, carbsG: 38, fatG: 18, fiberG: 2 },
  { name: "Cheese Whiz (2 tbsp)", category: "Condiment/Processed", calories: 90, proteinG: 4, carbsG: 3, fatG: 7, fiberG: 0 },
  { name: "Cheesecake (1 slice)", category: "Dessert", calories: 320, proteinG: 5, carbsG: 28, fatG: 21, fiberG: 1 },
  { name: "Cheesy Grits (1 cup)", category: "Meal/Grain", calories: 210, proteinG: 6, carbsG: 34, fatG: 6, fiberG: 2 },
  { name: "Cherries (1 cup)", category: "Fruit", calories: 77, proteinG: 1.6, carbsG: 19, fatG: 0.5, fiberG: 2.5 },
  { name: "Chicken & Rice Soup (1 can)", category: "Meal/Processed", calories: 130, proteinG: 7, carbsG: 18, fatG: 3, fiberG: 2 },
  { name: "Chicken Alfredo (1.5 cups)", category: "Meal/Pasta", calories: 680, proteinG: 35, carbsG: 45, fatG: 38, fiberG: 4 },
  { name: "Chicken Breast (4oz roasted)", category: "Protein/Meat", calories: 185, proteinG: 35, carbsG: 0, fatG: 4, fiberG: 0 },
  { name: "Chicken Kebab (2 skewers)", category: "Meal/Meat", calories: 280, proteinG: 30, carbsG: 8, fatG: 14, fiberG: 3 },
  { name: "Chicken Liver (2 oz cooked)", category: "Protein/Meat", calories: 91, proteinG: 13.6, carbsG: 0.6, fatG: 3.6, fiberG: 0 },
  { name: "Chicken McNuggets (6 pcs)", category: "Meal/Processed", calories: 270, proteinG: 15, carbsG: 16, fatG: 16, fiberG: 1 },
  { name: "Chicken Milanesa (1 serving)", category: "Meal/Meat", calories: 450, proteinG: 35, carbsG: 30, fatG: 22, fiberG: 3 },
  { name: "Chicken Noodle Soup (1 can)", category: "Meal/Processed", calories: 150, proteinG: 7, carbsG: 18, fatG: 5, fiberG: 2 },
  { name: "Chicken Parm Sandwich", category: "Meal/Processed", calories: 650, proteinG: 40, carbsG: 55, fatG: 30, fiberG: 6 },
  { name: "Chicken Piccata (1 serving)", category: "Meal/Meat", calories: 350, proteinG: 30, carbsG: 10, fatG: 20, fiberG: 1 },
  { name: "Chicken Salad Sandwich", category: "Meal/Processed", calories: 420, proteinG: 20, carbsG: 35, fatG: 20, fiberG: 3 },
  { name: "Chicken Thigh (1 roasted)", category: "Protein/Meat", calories: 210, proteinG: 24, carbsG: 0, fatG: 13, fiberG: 0 },
  { name: "Chicken Tikka Masala (1.5 cups)", category: "Meal/Meat", calories: 480, proteinG: 30, carbsG: 20, fatG: 30, fiberG: 5 },
  { name: "Chicken Wrap (with tortilla)", category: "Meal/Processed", calories: 410, proteinG: 25, carbsG: 38, fatG: 17, fiberG: 5 },
  { name: "Chickpeas (1/2 cup canned)", category: "Legume", calories: 135, proteinG: 7, carbsG: 22, fatG: 2, fiberG: 6 },
  { name: "Chili Powder (1 tsp)", category: "Condiment", calories: 8, proteinG: 0.3, carbsG: 1.4, fatG: 0.4, fiberG: 0.9 },
  { name: "Chimichurri (1 tbsp)", category: "Condiment", calories: 45, proteinG: 0.1, carbsG: 0.5, fatG: 4.5, fiberG: 0.2 },
  { name: "Chocolate (Hershey's bar 1 segment)", category: "Dessert", calories: 25, proteinG: 0.3, carbsG: 3, fatG: 1.5, fiberG: 0.2 },
  { name: "Chocolate Chip Cookie (1 large)", category: "Dessert", calories: 220, proteinG: 2.5, carbsG: 30, fatG: 11, fiberG: 1.5 },
  { name: "Chocolate Croissant", category: "Dessert", calories: 350, proteinG: 6, carbsG: 40, fatG: 19, fiberG: 3 },
  { name: "Chocolate Donut (1 medium)", category: "Dessert", calories: 300, proteinG: 4, carbsG: 35, fatG: 17, fiberG: 2 },
  { name: "Chocolate Milk (1 cup)", category: "Beverage/Dairy", calories: 200, proteinG: 8, carbsG: 26, fatG: 8, fiberG: 1 },
  { name: "Chocolate Pudding (1/2 cup)", category: "Dessert", calories: 150, proteinG: 2, carbsG: 28, fatG: 4, fiberG: 2 },
  { name: "Chocolate Sauce (1 tbsp dipping)", category: "Condiment", calories: 50, proteinG: 0.5, carbsG: 10, fatG: 1.5, fiberG: 1 },
  { name: "Choripan (1 sandwich)", category: "Meal/Processed", calories: 550, proteinG: 20, carbsG: 40, fatG: 35, fiberG: 3 },
  { name: "Chorizo (1 oz in paella)", category: "Protein/Meat", calories: 130, proteinG: 6, carbsG: 1, fatG: 11, fiberG: 0 },
  { name: "Churros (2 sticks)", category: "Dessert", calories: 240, proteinG: 3, carbsG: 30, fatG: 12, fiberG: 1.5 },
  { name: "Chutney (Mango 1 tbsp)", category: "Condiment", calories: 45, proteinG: 0.1, carbsG: 11, fatG: 0.1, fiberG: 0.5 },
  { name: "Cilantro (2 tbsp garnish)", category: "Condiment", calories: 1, proteinG: 0.1, carbsG: 0, fatG: 0, fiberG: 0.1 },
  { name: "Cinnamon Sugar (1 tsp)", category: "Condiment", calories: 20, proteinG: 0, carbsG: 5, fatG: 0, fiberG: 0 },
  { name: "Clam Chowder (1 cup)", category: "Meal/Seafood", calories: 200, proteinG: 10, carbsG: 18, fatG: 9, fiberG: 1 },
  { name: "Club Sandwich", category: "Meal/Processed", calories: 580, proteinG: 35, carbsG: 40, fatG: 30, fiberG: 5 },
  { name: "Club Soda (2 oz)", category: "Beverage", calories: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Coarse Salt (garnish)", category: "Condiment", calories: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Cobb Salad", category: "Meal/Protein", calories: 510, proteinG: 30, carbsG: 12, fatG: 38, fiberG: 7 },
  { name: "Cocktail Sauce (2 tbsp)", category: "Condiment", calories: 30, proteinG: 0.5, carbsG: 7, fatG: 0, fiberG: 0.5 },
  { name: "Coconut (shredded 1/4 cup)", category: "Fruit", calories: 110, proteinG: 1, carbsG: 4.5, fatG: 10.5, fiberG: 2 },
  { name: "Coconut (shredded garnish)", category: "Fruit", calories: 10, proteinG: 0.1, carbsG: 0.5, fatG: 1, fiberG: 0.2 },
  { name: "Coconut Flakes (1 tbsp topping)", category: "Fruit", calories: 35, proteinG: 0.3, carbsG: 1.5, fatG: 3.3, fiberG: 0.7 },
  { name: "Coconut Milk (1/4 cup canned)", category: "Condiment", calories: 111, proteinG: 1.1, carbsG: 2.9, fatG: 11.6, fiberG: 0.5 },
  { name: "Coconut Shrimp (5 pcs)", category: "Meal/Seafood", calories: 320, proteinG: 10, carbsG: 25, fatG: 20, fiberG: 3 },
  { name: "Coconut Water (1 cup)", category: "Beverage", calories: 46, proteinG: 1.7, carbsG: 8.9, fatG: 0.5, fiberG: 2.6 },
  { name: "Cod (4oz baked)", category: "Protein/Fish", calories: 95, proteinG: 20, carbsG: 0, fatG: 0.8, fiberG: 0 },
  { name: "Coffee (black)", category: "Beverage", calories: 5, proteinG: 0.3, carbsG: 0, fatG: 0.1, fiberG: 0 },
  { name: "Coffee (with cream/sugar)", category: "Beverage", calories: 50, proteinG: 0.5, carbsG: 5, fatG: 3, fiberG: 0 },
  { name: "Coffee Beans (3 garnish)", category: "Snack", calories: 2, proteinG: 0.1, carbsG: 0.3, fatG: 0, fiberG: 0.1 },
  { name: "Coffee Liqueur (1 oz)", category: "Beverage", calories: 100, proteinG: 0, carbsG: 15, fatG: 0, fiberG: 0 },
  { name: "Collard Greens (1 cup cooked)", category: "Vegetable", calories: 60, proteinG: 5, carbsG: 10, fatG: 1, fiberG: 7 },
  { name: "Collard Greens (with ham hock)", category: "Vegetable", calories: 180, proteinG: 10, carbsG: 15, fatG: 9, fiberG: 8 },
  { name: "Congee (1 cup plain)", category: "Meal/Grain", calories: 130, proteinG: 2.5, carbsG: 28, fatG: 1, fiberG: 1 },
  { name: "Coriander (1 tsp)", category: "Condiment", calories: 5, proteinG: 0.1, carbsG: 1, fatG: 0.2, fiberG: 0.5 },
  { name: "Corn (1 cup)", category: "Vegetable", calories: 132, proteinG: 4.7, carbsG: 30, fatG: 1.8, fiberG: 3.6 },
  { name: "Corn Flakes (1 cup)", category: "Grain", calories: 100, proteinG: 2, carbsG: 24, fatG: 0, fiberG: 1 },
  { name: "Corn Nuts (1 oz)", category: "Snack/Processed", calories: 130, proteinG: 2, carbsG: 23, fatG: 4, fiberG: 2 },
  { name: "Corn on the Cob (1 large)", category: "Vegetable", calories: 125, proteinG: 5, carbsG: 29, fatG: 1.5, fiberG: 3 },
  { name: "Corn Tortilla (1 medium)", category: "Grain", calories: 52, proteinG: 1.4, carbsG: 11.2, fatG: 0.7, fiberG: 1.5 },
  { name: "Cottage Cheese (1 cup low fat)", category: "Dairy", calories: 160, proteinG: 28, carbsG: 6, fatG: 2.5, fiberG: 0 },
  { name: "Cottage Cheese (1/2 cup)", category: "Dairy", calories: 90, proteinG: 12, carbsG: 5, fatG: 3, fiberG: 0 },
  { name: "Crab Cakes (2 medium)", category: "Meal/Seafood", calories: 340, proteinG: 20, carbsG: 18, fatG: 20, fiberG: 1 },
  { name: "Crackers (5 whole wheat)", category: "Grain/Processed", calories: 90, proteinG: 2, carbsG: 14, fatG: 3, fiberG: 2 },
  { name: "Cranberry Juice (1 cup)", category: "Beverage", calories: 130, proteinG: 0, carbsG: 33, fatG: 0, fiberG: 0 },
  { name: "Cream Cheese (2 tbsp)", category: "Dairy", calories: 100, proteinG: 2, carbsG: 2, fatG: 10, fiberG: 0 },
  { name: "Creamed Spinach (1/2 cup)", category: "Vegetable", calories: 190, proteinG: 5, carbsG: 8, fatG: 16, fiberG: 3 },
  { name: "Crepe (1 plain)", category: "Grain", calories: 90, proteinG: 3.5, carbsG: 14, fatG: 2, fiberG: 0.5 },
  { name: "Croutons (1/4 cup)", category: "Grain", calories: 50, proteinG: 1.5, carbsG: 7, fatG: 2, fiberG: 0.5 },
  { name: "Croutons (Garlic 1/4 cup)", category: "Grain", calories: 50, proteinG: 1.5, carbsG: 7, fatG: 2, fiberG: 0.5 },
  { name: "Crushed Tomatoes (1/2 cup sauce)", category: "Vegetable", calories: 20, proteinG: 1, carbsG: 4, fatG: 0, fiberG: 1.5 },
  { name: "Cucumber (1/4 cup side)", category: "Vegetable", calories: 8, proteinG: 0.3, carbsG: 1.8, fatG: 0, fiberG: 0.2 },
  { name: "Cucumber Salad (1/2 cup)", category: "Vegetable", calories: 40, proteinG: 1, carbsG: 5, fatG: 2, fiberG: 1 },
  { name: "Cucumber Slices (1 cup)", category: "Vegetable", calories: 16, proteinG: 0.7, carbsG: 3.6, fatG: 0.1, fiberG: 0.5 },
  { name: "Cumin (1 tsp)", category: "Condiment", calories: 8, proteinG: 0.3, carbsG: 1.5, fatG: 0.5, fiberG: 0.4 },
  { name: "Cupcake (Vanilla 1 medium)", category: "Dessert", calories: 240, proteinG: 2, carbsG: 35, fatG: 11, fiberG: 1 },
  { name: "Custard (1/4 cup)", category: "Condiment", calories: 80, proteinG: 3, carbsG: 10, fatG: 3, fiberG: 0 },
  { name: "Danish (Cheese 1 medium)", category: "Dessert", calories: 340, proteinG: 7, carbsG: 38, fatG: 18, fiberG: 2 },
  { name: "Dark Chocolate (1 oz 70%)", category: "Dessert", calories: 170, proteinG: 2.2, carbsG: 13, fatG: 12, fiberG: 3 },
  { name: "Dates (2 medium Medjool)", category: "Fruit", calories: 133, proteinG: 0.8, carbsG: 36, fatG: 0.1, fiberG: 3.2 },
  { name: "Diet Soda (1 can)", category: "Beverage", calories: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Dim Sum (Siu Mai 3 pcs)", category: "Meal/Processed", calories: 180, proteinG: 12, carbsG: 10, fatG: 10, fiberG: 2 },
  { name: "Duck (3oz roasted)", category: "Protein/Meat", calories: 285, proteinG: 16, carbsG: 0, fatG: 24, fiberG: 0 },
  { name: "Dulce de Leche (1 tbsp filling)", category: "Condiment", calories: 65, proteinG: 1, carbsG: 12, fatG: 1.5, fiberG: 0 },
  { name: "Edamame (in pod 1 cup)", category: "Legume", calories: 120, proteinG: 11, carbsG: 9, fatG: 5, fiberG: 5 },
  { name: "Egg Drop Soup (1 cup)", category: "Meal/Vegetable", calories: 65, proteinG: 5, carbsG: 6, fatG: 2, fiberG: 0.5 },
  { name: "Egg Noodles (1 cup cooked)", category: "Grain", calories: 220, proteinG: 8, carbsG: 40, fatG: 3, fiberG: 2 },
  { name: "Egg White (in drink)", category: "Condiment", calories: 17, proteinG: 3.6, carbsG: 0.2, fatG: 0, fiberG: 0 },
  { name: "Egg Yolk (1 large in sauce)", category: "Protein", calories: 55, proteinG: 2.7, carbsG: 0.6, fatG: 4.5, fiberG: 0 },
  { name: "Eggo Waffle (2 waffles)", category: "Grain/Processed", calories: 180, proteinG: 4, carbsG: 30, fatG: 5, fiberG: 1 },
  { name: "Eggplant (1/2 cup in caponata)", category: "Vegetable", calories: 40, proteinG: 0.5, carbsG: 6, fatG: 2, fiberG: 2 },
  { name: "Eggs Benedict (1 serving)", category: "Meal/Protein", calories: 600, proteinG: 25, carbsG: 30, fatG: 40, fiberG: 3 },
  { name: "Empanada (Beef 1 medium)", category: "Meal/Processed", calories: 290, proteinG: 10, carbsG: 28, fatG: 16, fiberG: 3 },
  { name: "English Muffin (whole wheat)", category: "Grain", calories: 134, proteinG: 6, carbsG: 26, fatG: 1, fiberG: 4.4 },
  { name: "Espresso (1 oz in drink)", category: "Beverage", calories: 3, proteinG: 0.3, carbsG: 0, fatG: 0.1, fiberG: 0 },
  { name: "Espresso (double shot)", category: "Beverage", calories: 5, proteinG: 0.5, carbsG: 0, fatG: 0.1, fiberG: 0 },
  { name: "Espresso (for dipping)", category: "Beverage", calories: 2, proteinG: 0.2, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Espresso Martini (1 drink)", category: "Beverage", calories: 280, proteinG: 0.5, carbsG: 25, fatG: 0, fiberG: 0 },
  { name: "Falafel (3 pieces)", category: "Meal/Vegetarian", calories: 180, proteinG: 6, carbsG: 18, fatG: 9, fiberG: 4 },
  { name: "Fattoush Salad (1.5 cups)", category: "Meal/Vegetarian", calories: 250, proteinG: 5, carbsG: 25, fatG: 15, fiberG: 6 },
  { name: "Feta Cheese (1 oz)", category: "Dairy", calories: 75, proteinG: 4, carbsG: 1.2, fatG: 6.1, fiberG: 0 },
  { name: "Figs (2 medium)", category: "Fruit", calories: 74, proteinG: 0.6, carbsG: 19.2, fatG: 0.3, fiberG: 2.9 },
  { name: "Fiorentina Steak (3oz portion)", category: "Protein/Meat", calories: 230, proteinG: 24, carbsG: 0, fatG: 15, fiberG: 0 },
  { name: "Fish Sauce (1 tsp)", category: "Condiment", calories: 5, proteinG: 0.4, carbsG: 0.5, fatG: 0, fiberG: 0 },
  { name: "Fish Tacos (2 tacos)", category: "Meal/Fish", calories: 420, proteinG: 25, carbsG: 40, fatG: 18, fiberG: 6 },
  { name: "Flan (1 slice)", category: "Dessert", calories: 220, proteinG: 6, carbsG: 35, fatG: 7, fiberG: 0 },
  { name: "Focaccia (1 square)", category: "Grain", calories: 250, proteinG: 8, carbsG: 40, fatG: 7, fiberG: 2 },
  { name: "French Bread (2 slices)", category: "Grain", calories: 180, proteinG: 6, carbsG: 36, fatG: 1, fiberG: 2 },
  { name: "French Fries (as side)", category: "Vegetable/Processed", calories: 200, proteinG: 2, carbsG: 25, fatG: 10, fiberG: 2 },
  { name: "French Fries (medium)", category: "Vegetable/Processed", calories: 340, proteinG: 4, carbsG: 44, fatG: 17, fiberG: 4 },
  { name: "French Fries (side)", category: "Vegetable/Processed", calories: 340, proteinG: 4, carbsG: 44, fatG: 17, fiberG: 4 },
  { name: "French Onion Soup (1 cup)", category: "Meal", calories: 150, proteinG: 6, carbsG: 15, fatG: 7, fiberG: 2 },
  { name: "Fresh Mozzarella (1 oz)", category: "Dairy", calories: 72, proteinG: 5, carbsG: 0.8, fatG: 5, fiberG: 0 },
  { name: "Fried Okra (1 cup)", category: "Vegetable", calories: 220, proteinG: 4, carbsG: 25, fatG: 12, fiberG: 5 },
  { name: "Fried Pita (1/2 pita in salad)", category: "Grain", calories: 80, proteinG: 2, carbsG: 12, fatG: 3, fiberG: 1 },
  { name: "Frosting (Vanilla 2 tbsp)", category: "Condiment", calories: 140, proteinG: 0, carbsG: 22, fatG: 6, fiberG: 0 },
  { name: "Fruit Cocktail (canned 1 cup)", category: "Fruit", calories: 110, proteinG: 1, carbsG: 28, fatG: 0, fiberG: 2 },
  { name: "Garlic (1 clove in beans)", category: "Vegetable", calories: 4, proteinG: 0.2, carbsG: 0.9, fatG: 0, fiberG: 0.1 },
  { name: "Garlic (1 clove)", category: "Vegetable", calories: 4, proteinG: 0.2, carbsG: 0.9, fatG: 0, fiberG: 0.1 },
  { name: "Garlic (1/2 clove in pesto)", category: "Vegetable", calories: 2, proteinG: 0.1, carbsG: 0.5, fatG: 0, fiberG: 0 },
  { name: "Garlic Bread (1 slice)", category: "Grain", calories: 150, proteinG: 4, carbsG: 18, fatG: 7, fiberG: 1 },
  { name: "Garlic Sauce (1 tbsp)", category: "Condiment", calories: 90, proteinG: 0.1, carbsG: 1, fatG: 10, fiberG: 0 },
  { name: "Garlic Sauce (Toum 1 tbsp)", category: "Condiment", calories: 90, proteinG: 0.1, carbsG: 1, fatG: 10, fiberG: 0 },
  { name: "Gazpacho (1 cup)", category: "Meal/Soup", calories: 90, proteinG: 2, carbsG: 12, fatG: 4, fiberG: 3 },
  { name: "Gelato (Pistachio 1/2 cup)", category: "Dessert", calories: 220, proteinG: 5, carbsG: 24, fatG: 12, fiberG: 2 },
  { name: "Gin (1 oz)", category: "Beverage", calories: 70, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Gin & Tonic (1 drink)", category: "Beverage", calories: 170, proteinG: 0, carbsG: 13, fatG: 0, fiberG: 0 },
  { name: "Ginger Ale (1 can)", category: "Beverage", calories: 124, proteinG: 0, carbsG: 32, fatG: 0, fiberG: 0 },
  { name: "Gnocchi (1 cup)", category: "Meal/Pasta", calories: 210, proteinG: 4.5, carbsG: 45, fatG: 1.5, fiberG: 3 },
  { name: "Gnocchi alla Sorrentina (1.5 cups)", category: "Meal/Pasta", calories: 450, proteinG: 15, carbsG: 60, fatG: 18, fiberG: 6 },
  { name: "Goat Cheese (1 oz)", category: "Dairy", calories: 103, proteinG: 6.1, carbsG: 0.1, fatG: 8.5, fiberG: 0 },
  { name: "Gochugaru (1 tsp)", category: "Condiment", calories: 10, proteinG: 0.3, carbsG: 1.8, fatG: 0.3, fiberG: 0.5 },
  { name: "Gochujang (1 tbsp)", category: "Condiment", calories: 30, proteinG: 0.5, carbsG: 6, fatG: 0, fiberG: 0.5 },
  { name: "Gorgonzola Cheese (1 oz)", category: "Dairy", calories: 100, proteinG: 6, carbsG: 0.7, fatG: 8, fiberG: 0 },
  { name: "Graham Cracker (1 large rectangle)", category: "Grain/Processed", calories: 60, proteinG: 1, carbsG: 11, fatG: 1.5, fiberG: 0.5 },
  { name: "Granola (1/4 cup topping)", category: "Grain", calories: 120, proteinG: 3, carbsG: 15, fatG: 6, fiberG: 3 },
  { name: "Grapefruit (1/2 medium)", category: "Fruit", calories: 52, proteinG: 1.1, carbsG: 13.2, fatG: 0.2, fiberG: 2 },
  { name: "Grapes (1 cup)", category: "Fruit", calories: 104, proteinG: 1.1, carbsG: 27, fatG: 0.2, fiberG: 1.4 },
  { name: "Greek Yogurt (plain 1 cup)", category: "Dairy", calories: 150, proteinG: 25, carbsG: 8, fatG: 3, fiberG: 0 },
  { name: "Green Beans (1 cup)", category: "Vegetable", calories: 31, proteinG: 1.8, carbsG: 7, fatG: 0.2, fiberG: 2.7 },
  { name: "Green Beans (1/2 cup w/ pasta)", category: "Vegetable", calories: 15, proteinG: 0.9, carbsG: 3.5, fatG: 0.1, fiberG: 1.3 },
  { name: "Green Curry Paste (1 tbsp)", category: "Condiment", calories: 30, proteinG: 0.5, carbsG: 2, fatG: 2.5, fiberG: 1 },
  { name: "Green Onion (1 tbsp garnish)", category: "Vegetable", calories: 3, proteinG: 0.2, carbsG: 0.7, fatG: 0, fiberG: 0.2 },
  { name: "Green Peas (1/2 cup)", category: "Legume", calories: 62, proteinG: 4.1, carbsG: 11.1, fatG: 0.2, fiberG: 4.4 },
  { name: "Gremolata (1 tbsp)", category: "Condiment", calories: 15, proteinG: 0.5, carbsG: 1, fatG: 1, fiberG: 0.5 },
  { name: "Grilled Cheese Sandwich", category: "Meal/Processed", calories: 390, proteinG: 15, carbsG: 32, fatG: 22, fiberG: 3 },
  { name: "Grilled Chicken Salad", category: "Meal/Protein", calories: 350, proteinG: 30, carbsG: 10, fatG: 20, fiberG: 5 },
  { name: "Grits (1 cup cooked)", category: "Grain", calories: 150, proteinG: 3, carbsG: 32, fatG: 1, fiberG: 2 },
  { name: "Ground Beef (2 oz in sauce)", category: "Protein/Meat", calories: 140, proteinG: 11, carbsG: 0, fatG: 10, fiberG: 0 },
  { name: "Ground Lamb (1 oz filling)", category: "Protein/Meat", calories: 80, proteinG: 5.5, carbsG: 0, fatG: 6, fiberG: 0 },
  { name: "Guacamole (1/4 cup)", category: "Vegetable/Condiment", calories: 90, proteinG: 1, carbsG: 4, fatG: 8, fiberG: 3 },
  { name: "Guanciale (1 oz)", category: "Protein/Meat", calories: 170, proteinG: 3, carbsG: 0, fatG: 18, fiberG: 0 },
  { name: "Guava", category: "Fruit", calories: 68, proteinG: 2.6, carbsG: 14.3, fatG: 0.9, fiberG: 5.4 },
  { name: "Gummy Bears (10 pcs)", category: "Snack/Dessert", calories: 100, proteinG: 2, carbsG: 22, fatG: 0, fiberG: 0 },
  { name: "Gyro (1 sandwich)", category: "Meal/Meat", calories: 600, proteinG: 25, carbsG: 55, fatG: 30, fiberG: 5 },
  { name: "Halibut (4oz baked)", category: "Protein/Fish", calories: 125, proteinG: 24, carbsG: 0, fatG: 2.5, fiberG: 0 },
  { name: "Ham (3oz deli sliced)", category: "Protein/Meat", calories: 110, proteinG: 16, carbsG: 2, fatG: 4, fiberG: 0 },
  { name: "Ham & Cheese Croissant", category: "Meal/Processed", calories: 400, proteinG: 15, carbsG: 35, fatG: 22, fiberG: 2 },
  { name: "Hard-Boiled Egg (1 large)", category: "Protein", calories: 78, proteinG: 6.3, carbsG: 0.6, fatG: 5.3, fiberG: 0 },
  { name: "Hash Browns (1 cup)", category: "Vegetable", calories: 330, proteinG: 3, carbsG: 38, fatG: 19, fiberG: 3 },
  { name: "Hoisin Sauce (1 tbsp)", category: "Condiment", calories: 35, proteinG: 0.3, carbsG: 8, fatG: 0.2, fiberG: 0.1 },
  { name: "Hollandaise Sauce (1 tbsp)", category: "Condiment", calories: 55, proteinG: 0.5, carbsG: 0.2, fatG: 6, fiberG: 0 },
  { name: "Hollandaise Sauce (2 tbsp)", category: "Condiment", calories: 110, proteinG: 1, carbsG: 0.5, fatG: 12, fiberG: 0 },
  { name: "Honey (1 tbsp)", category: "Condiment", calories: 64, proteinG: 0.1, carbsG: 17.3, fatG: 0, fiberG: 0 },
  { name: "Honey (1 tsp drizzle)", category: "Condiment", calories: 21, proteinG: 0, carbsG: 5.8, fatG: 0, fiberG: 0 },
  { name: "Horchata (1 cup)", category: "Beverage", calories: 140, proteinG: 2, carbsG: 25, fatG: 3, fiberG: 1 },
  { name: "Hot Chocolate (1 cup)", category: "Beverage", calories: 200, proteinG: 3, carbsG: 30, fatG: 8, fiberG: 2 },
  { name: "Hot Sauce (1 tsp Tabasco)", category: "Condiment", calories: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Hummus (1/4 cup)", category: "Legume", calories: 130, proteinG: 5, carbsG: 10, fatG: 8, fiberG: 4 },
  { name: "Hummus (2 tbsp)", category: "Legume", calories: 70, proteinG: 2, carbsG: 4, fatG: 5, fiberG: 2 },
  { name: "Hummus Wrap (large)", category: "Meal/Vegetarian", calories: 450, proteinG: 15, carbsG: 60, fatG: 18, fiberG: 12 },
  { name: "Ice Cream (1/2 cup vanilla)", category: "Dairy/Dessert", calories: 145, proteinG: 2.5, carbsG: 17, fatG: 7.5, fiberG: 0.5 },
  { name: "Iced Tea (Sweetened 16oz)", category: "Beverage", calories: 180, proteinG: 0, carbsG: 46, fatG: 0, fiberG: 0 },
  { name: "Italian Dressing (2 tbsp)", category: "Condiment", calories: 70, proteinG: 0, carbsG: 3, fatG: 7, fiberG: 0 },
  { name: "Italian Sausage (1 link)", category: "Protein/Meat", calories: 200, proteinG: 12, carbsG: 3, fatG: 16, fiberG: 0 },
  { name: "Jalapeno (1 tbsp sliced)", category: "Vegetable", calories: 4, proteinG: 0.1, carbsG: 0.8, fatG: 0.1, fiberG: 0.4 },
  { name: "Jasmine Rice (1 cup cooked)", category: "Grain", calories: 205, proteinG: 4.3, carbsG: 45, fatG: 0.4, fiberG: 0.6 },
  { name: "Jelly (1 tbsp grape)", category: "Condiment", calories: 50, proteinG: 0, carbsG: 13, fatG: 0, fiberG: 0.1 },
  { name: "Jicama (1 cup sticks)", category: "Vegetable", calories: 46, proteinG: 0.9, carbsG: 10.6, fatG: 0.1, fiberG: 5.8 },
  { name: "Kale (1 cup in soup)", category: "Vegetable", calories: 33, proteinG: 2.9, carbsG: 6, fatG: 0.6, fiberG: 2 },
  { name: "Kefir (Plain 1 cup)", category: "Beverage/Dairy", calories: 104, proteinG: 10, carbsG: 10, fatG: 2.5, fiberG: 0 },
  { name: "Ketchup (1 packet)", category: "Condiment", calories: 10, proteinG: 0.1, carbsG: 2.5, fatG: 0, fiberG: 0.1 },
  { name: "Ketchup (1 tbsp)", category: "Condiment", calories: 20, proteinG: 0.2, carbsG: 5, fatG: 0.1, fiberG: 0.2 },
  { name: "Kibbeh (1 piece fried)", category: "Meal/Meat", calories: 230, proteinG: 9, carbsG: 20, fatG: 13, fiberG: 3 },
  { name: "Kimchi (1/2 cup)", category: "Vegetable", calories: 22, proteinG: 1.7, carbsG: 4, fatG: 0.4, fiberG: 2.4 },
  { name: "Kimchi Jjigae (1 bowl)", category: "Meal/Soup", calories: 350, proteinG: 15, carbsG: 20, fatG: 22, fiberG: 5 },
  { name: "Kiwifruit (1 medium)", category: "Fruit", calories: 46, proteinG: 0.9, carbsG: 11.1, fatG: 0.4, fiberG: 2.3 },
  { name: "Kombucha (1 cup)", category: "Beverage", calories: 30, proteinG: 0, carbsG: 7, fatG: 0, fiberG: 0 },
  { name: "Kombucha (16 oz)", category: "Beverage", calories: 60, proteinG: 0, carbsG: 14, fatG: 0, fiberG: 0 },
  { name: "Labneh (2 tbsp)", category: "Dairy", calories: 60, proteinG: 4, carbsG: 2, fatG: 4, fiberG: 0 },
  { name: "Lasagna (1 serving meat)", category: "Meal/Pasta", calories: 350, proteinG: 20, carbsG: 30, fatG: 17, fiberG: 4 },
  { name: "Lassi (Mango 1 cup)", category: "Beverage", calories: 180, proteinG: 5, carbsG: 30, fatG: 4, fiberG: 1 },
  { name: "Lemon Bar (1 square)", category: "Dessert", calories: 150, proteinG: 1.5, carbsG: 22, fatG: 6, fiberG: 0.5 },
  { name: "Lemon Juice (1 tbsp dressing)", category: "Condiment", calories: 4, proteinG: 0.1, carbsG: 1.3, fatG: 0, fiberG: 0.1 },
  { name: "Lemon Juice (1 tsp in soup)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.4, fatG: 0, fiberG: 0 },
  { name: "Lemon Slice (garnish)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.3, fatG: 0, fiberG: 0.1 },
  { name: "Lemon Wedge (for calamari)", category: "Condiment", calories: 3, proteinG: 0.1, carbsG: 1, fatG: 0, fiberG: 0.3 },
  { name: "Lemonade (1 cup)", category: "Beverage", calories: 99, proteinG: 0.1, carbsG: 26, fatG: 0, fiberG: 0.1 },
  { name: "Lentil Soup (1 can)", category: "Meal/Legume", calories: 230, proteinG: 15, carbsG: 35, fatG: 3, fiberG: 12 },
  { name: "Lentil Soup (1 cup Middle Eastern)", category: "Meal/Legume", calories: 200, proteinG: 10, carbsG: 30, fatG: 5, fiberG: 10 },
  { name: "Lettuce (Romaine 2 cups)", category: "Vegetable", calories: 16, proteinG: 1, carbsG: 3, fatG: 0.3, fiberG: 2 },
  { name: "Lime (juice of 1)", category: "Condiment", calories: 11, proteinG: 0.2, carbsG: 3.7, fatG: 0, fiberG: 0.4 },
  { name: "Lime Juice (1 tbsp)", category: "Condiment", calories: 4, proteinG: 0.1, carbsG: 1.3, fatG: 0, fiberG: 0.1 },
  { name: "Lime Wedge (garnish)", category: "Condiment", calories: 3, proteinG: 0.1, carbsG: 1, fatG: 0, fiberG: 0.3 },
  { name: "Limoncello (1.5 oz shot)", category: "Beverage", calories: 150, proteinG: 0, carbsG: 18, fatG: 0, fiberG: 0 },
  { name: "Lobster (3oz steamed)", category: "Protein/Seafood", calories: 76, proteinG: 16, carbsG: 0, fatG: 0.7, fiberG: 0 },
  { name: "Lobster Bisque (1 cup)", category: "Meal/Seafood", calories: 250, proteinG: 8, carbsG: 12, fatG: 18, fiberG: 1 },
  { name: "Lomo Saltado (1.5 cups)", category: "Meal/Meat", calories: 500, proteinG: 35, carbsG: 45, fatG: 22, fiberG: 5 },
  { name: "Macadamia Nuts (1 oz)", category: "Nut", calories: 204, proteinG: 2.2, carbsG: 3.9, fatG: 21.5, fiberG: 2.4 },
  { name: "Macaroni & Cheese (1 cup)", category: "Meal/Pasta", calories: 350, proteinG: 10, carbsG: 40, fatG: 17, fiberG: 2 },
  { name: "Macaroni Salad (1 cup)", category: "Meal/Pasta", calories: 380, proteinG: 8, carbsG: 30, fatG: 25, fiberG: 3 },
  { name: "Mackerel (3oz cooked)", category: "Protein/Fish", calories: 175, proteinG: 16, carbsG: 0, fatG: 12, fiberG: 0 },
  { name: "Malva Pudding (1 slice)", category: "Dessert", calories: 380, proteinG: 5, carbsG: 60, fatG: 14, fiberG: 2 },
  { name: "Manakeesh (Za'atar 1 small)", category: "Meal/Vegetarian", calories: 300, proteinG: 7, carbsG: 45, fatG: 10, fiberG: 4 },
  { name: "Mandarin Orange (1 medium)", category: "Fruit", calories: 37, proteinG: 0.6, carbsG: 9.3, fatG: 0.2, fiberG: 1.3 },
  { name: "Mango (1 cup slices)", category: "Fruit", calories: 99, proteinG: 1.4, carbsG: 24.7, fatG: 0.6, fiberG: 2.6 },
  { name: "Manicotti (2 shells cheese)", category: "Meal/Pasta", calories: 380, proteinG: 20, carbsG: 35, fatG: 18, fiberG: 4 },
  { name: "Maple Syrup (1 tbsp)", category: "Condiment", calories: 52, proteinG: 0, carbsG: 13.5, fatG: 0, fiberG: 0 },
  { name: "Maple Syrup (2 tbsp)", category: "Condiment", calories: 104, proteinG: 0, carbsG: 27, fatG: 0, fiberG: 0 },
  { name: "Margarita (1 drink, 4oz)", category: "Beverage", calories: 200, proteinG: 0.1, carbsG: 20, fatG: 0, fiberG: 0.1 },
  { name: "Marshmallow (1 large)", category: "Dessert", calories: 23, proteinG: 0.1, carbsG: 5.8, fatG: 0, fiberG: 0 },
  { name: "Mashed Cauliflower (1 cup)", category: "Vegetable", calories: 140, proteinG: 5, carbsG: 12, fatG: 8, fiberG: 5 },
  { name: "Mashed Potatoes (1 cup)", category: "Vegetable", calories: 230, proteinG: 4, carbsG: 35, fatG: 8, fiberG: 3 },
  { name: "Mashed Potatoes (side)", category: "Vegetable", calories: 150, proteinG: 3, carbsG: 25, fatG: 4, fiberG: 2 },
  { name: "Matcha Latte (12 oz)", category: "Beverage", calories: 180, proteinG: 6, carbsG: 28, fatG: 5, fiberG: 2 },
  { name: "Mate (1 cup)", category: "Beverage", calories: 5, proteinG: 0.2, carbsG: 1, fatG: 0, fiberG: 0 },
  { name: "Mayonnaise (1 tbsp for dipping)", category: "Condiment", calories: 90, proteinG: 0.1, carbsG: 0.1, fatG: 10, fiberG: 0 },
  { name: "Mayonnaise (1 tbsp)", category: "Condiment", calories: 90, proteinG: 0.1, carbsG: 0.1, fatG: 10, fiberG: 0 },
  { name: "Meatball Sub (6 inch)", category: "Meal/Processed", calories: 580, proteinG: 28, carbsG: 55, fatG: 27, fiberG: 6 },
  { name: "Media Luna (1 pastry)", category: "Grain", calories: 190, proteinG: 4, carbsG: 25, fatG: 8, fiberG: 1 },
  { name: "Melted Butter (for lobster)", category: "Condiment", calories: 200, proteinG: 0.2, carbsG: 0, fatG: 22, fiberG: 0 },
  { name: "Mignonette Sauce (1 tbsp)", category: "Condiment", calories: 5, proteinG: 0, carbsG: 1, fatG: 0, fiberG: 0 },
  { name: "Milk (2%, 1 cup)", category: "Dairy", calories: 122, proteinG: 8, carbsG: 12, fatG: 5, fiberG: 0 },
  { name: "Mint (1 tbsp in tabouli)", category: "Condiment", calories: 1, proteinG: 0.1, carbsG: 0.1, fatG: 0, fiberG: 0.1 },
  { name: "Mint Chutney (1 tbsp)", category: "Condiment", calories: 5, proteinG: 0.2, carbsG: 0.5, fatG: 0, fiberG: 0.3 },
  { name: "Mint Tea (1 cup)", category: "Beverage", calories: 2, proteinG: 0.1, carbsG: 0.5, fatG: 0, fiberG: 0 },
  { name: "Mixed Nuts (1/4 cup)", category: "Nut", calories: 200, proteinG: 6, carbsG: 8, fatG: 18, fiberG: 3 },
  { name: "Mocha Latte (16oz)", category: "Beverage", calories: 360, proteinG: 12, carbsG: 48, fatG: 15, fiberG: 2 },
  { name: "Mozzarella (1 oz melted)", category: "Dairy", calories: 80, proteinG: 6, carbsG: 1, fatG: 6, fiberG: 0 },
  { name: "Mozzarella (1 slice)", category: "Dairy", calories: 80, proteinG: 6, carbsG: 1, fatG: 6, fiberG: 0 },
  { name: "Mozzarella (filling 0.5 oz)", category: "Dairy", calories: 40, proteinG: 3, carbsG: 0.5, fatG: 3, fiberG: 0 },
  { name: "Muffin (Blueberry 1 large)", category: "Grain/Dessert", calories: 380, proteinG: 5, carbsG: 55, fatG: 16, fiberG: 2 },
  { name: "Mushroom (White 1 cup sliced)", category: "Vegetable", calories: 15, proteinG: 2.2, carbsG: 2.3, fatG: 0.2, fiberG: 0.7 },
  { name: "Mussels (3oz steamed)", category: "Protein/Seafood", calories: 146, proteinG: 20, carbsG: 6, fatG: 4, fiberG: 0 },
  { name: "Mustard (1 tbsp, yellow)", category: "Condiment", calories: 10, proteinG: 0.5, carbsG: 1, fatG: 0.5, fiberG: 0.5 },
  { name: "Naan Bread (1 piece)", category: "Grain", calories: 260, proteinG: 8, carbsG: 45, fatG: 5, fiberG: 2 },
  { name: "Negroni (1 drink)", category: "Beverage", calories: 190, proteinG: 0, carbsG: 15, fatG: 0, fiberG: 0 },
  { name: "Nutella (1 tbsp)", category: "Condiment", calories: 100, proteinG: 1.5, carbsG: 11, fatG: 6, fiberG: 1 },
  { name: "Nutritional Yeast (1 tbsp)", category: "Condiment", calories: 20, proteinG: 3, carbsG: 2, fatG: 0, fiberG: 1 },
  { name: "Oat Milk (1 cup)", category: "Beverage/Dairy-Alt", calories: 120, proteinG: 3, carbsG: 16, fatG: 5, fiberG: 2 },
  { name: "Oatmeal (1 cup cooked)", category: "Grain", calories: 160, proteinG: 6, carbsG: 28, fatG: 3, fiberG: 4 },
  { name: "Olive (garnish)", category: "Fruit", calories: 5, proteinG: 0, carbsG: 0.1, fatG: 0.5, fiberG: 0.1 },
  { name: "Olive Oil (1 tbsp dressing)", category: "Condiment", calories: 120, proteinG: 0, carbsG: 0, fatG: 14, fiberG: 0 },
  { name: "Olive Oil (1 tbsp drizzle)", category: "Condiment", calories: 120, proteinG: 0, carbsG: 0, fatG: 14, fiberG: 0 },
  { name: "Olive Oil (1 tbsp on bread)", category: "Condiment", calories: 120, proteinG: 0, carbsG: 0, fatG: 14, fiberG: 0 },
  { name: "Olive Oil (1 tbsp)", category: "Condiment", calories: 120, proteinG: 0, carbsG: 0, fatG: 14, fiberG: 0 },
  { name: "Olive Oil (1 tsp garnish)", category: "Condiment", calories: 40, proteinG: 0, carbsG: 0, fatG: 4.5, fiberG: 0 },
  { name: "Olives (5 side)", category: "Fruit", calories: 35, proteinG: 0.2, carbsG: 1, fatG: 3.5, fiberG: 0.5 },
  { name: "Olives (Kalamata 5 large)", category: "Fruit", calories: 35, proteinG: 0.2, carbsG: 1, fatG: 3.5, fiberG: 0.5 },
  { name: "Onion (1/2 cup raw chopped)", category: "Vegetable", calories: 32, proteinG: 0.9, carbsG: 7.5, fatG: 0.1, fiberG: 1.4 },
  { name: "Onion (1/8 minced in sauce)", category: "Vegetable", calories: 5, proteinG: 0.1, carbsG: 1.2, fatG: 0, fiberG: 0.2 },
  { name: "Onion Rings (6 rings)", category: "Snack/Processed", calories: 280, proteinG: 4, carbsG: 30, fatG: 16, fiberG: 3 },
  { name: "Onions (sautéed 1/4 cup)", category: "Vegetable", calories: 30, proteinG: 0.5, carbsG: 5, fatG: 1, fiberG: 1 },
  { name: "Orange", category: "Fruit", calories: 62, proteinG: 1.2, carbsG: 15.4, fatG: 0.2, fiberG: 3.1 },
  { name: "Orange Juice (1 cup)", category: "Beverage", calories: 112, proteinG: 1.7, carbsG: 25.8, fatG: 0.5, fiberG: 0.7 },
  { name: "Orange Peel (garnish)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.2, fatG: 0, fiberG: 0.1 },
  { name: "Orange Sauce (1/4 cup for duck)", category: "Condiment", calories: 90, proteinG: 0.5, carbsG: 22, fatG: 0, fiberG: 0.5 },
  { name: "Orange Slice (garnish)", category: "Fruit", calories: 5, proteinG: 0.1, carbsG: 1, fatG: 0, fiberG: 0.2 },
  { name: "Oregano (1 tsp)", category: "Condiment", calories: 3, proteinG: 0.1, carbsG: 0.7, fatG: 0, fiberG: 0.2 },
  { name: "Osso Buco (1 serving)", category: "Meal/Meat", calories: 550, proteinG: 45, carbsG: 15, fatG: 30, fiberG: 4 },
  { name: "Oyster (1 medium raw)", category: "Protein/Seafood", calories: 8, proteinG: 1, carbsG: 0.5, fatG: 0.2, fiberG: 0 },
  { name: "Pad Thai (Chicken 1.5 cups)", category: "Meal/Pasta", calories: 550, proteinG: 25, carbsG: 60, fatG: 22, fiberG: 5 },
  { name: "Paella (1.5 cups seafood)", category: "Meal/Rice", calories: 550, proteinG: 30, carbsG: 70, fatG: 18, fiberG: 6 },
  { name: "Pancakes (2 medium)", category: "Grain", calories: 180, proteinG: 5, carbsG: 30, fatG: 5, fiberG: 1 },
  { name: "Pancetta (0.5 oz in sauce)", category: "Protein/Meat", calories: 45, proteinG: 1.5, carbsG: 0, fatG: 4.5, fiberG: 0 },
  { name: "Panettone (1 slice)", category: "Dessert", calories: 320, proteinG: 6, carbsG: 50, fatG: 12, fiberG: 3 },
  { name: "Pani Puri (6 pcs)", category: "Snack/Processed", calories: 200, proteinG: 4, carbsG: 35, fatG: 5, fiberG: 3 },
  { name: "Panna Cotta (1 serving)", category: "Dessert", calories: 300, proteinG: 4, carbsG: 25, fatG: 20, fiberG: 0 },
  { name: "Papaya (1 cup cubes)", category: "Fruit", calories: 62, proteinG: 0.6, carbsG: 15.7, fatG: 0.4, fiberG: 2.5 },
  { name: "Parmigiano-Reggiano (1 tbsp)", category: "Dairy", calories: 22, proteinG: 2, carbsG: 0.2, fatG: 1.5, fiberG: 0 },
  { name: "Parsley (1/4 cup in tabouli)", category: "Vegetable", calories: 5, proteinG: 0.3, carbsG: 1, fatG: 0.1, fiberG: 0.5 },
  { name: "Passion Fruit (1 fruit)", category: "Fruit", calories: 17, proteinG: 0.4, carbsG: 4.2, fatG: 0.1, fiberG: 1.9 },
  { name: "Pasta Salad (1 cup)", category: "Meal/Pasta", calories: 280, proteinG: 8, carbsG: 30, fatG: 14, fiberG: 4 },
  { name: "Pate (Mushroom 2 tbsp)", category: "Condiment", calories: 70, proteinG: 1, carbsG: 2, fatG: 7, fiberG: 1 },
  { name: "Peanut Butter (2 tbsp)", category: "Nut", calories: 190, proteinG: 7, carbsG: 8, fatG: 16, fiberG: 2 },
  { name: "Peanut Butter & Jelly Sandwich", category: "Meal/Processed", calories: 390, proteinG: 12, carbsG: 50, fatG: 17, fiberG: 5 },
  { name: "Peanut Sauce (2 tbsp)", category: "Condiment", calories: 80, proteinG: 2, carbsG: 4, fatG: 6, fiberG: 1 },
  { name: "Pear", category: "Fruit", calories: 101, proteinG: 0.6, carbsG: 27, fatG: 0.2, fiberG: 5.5 },
  { name: "Pecans (1 oz)", category: "Nut", calories: 196, proteinG: 2.6, carbsG: 3.9, fatG: 20.4, fiberG: 2.7 },
  { name: "Pecorino Cheese (1 tbsp)", category: "Dairy", calories: 25, proteinG: 1.5, carbsG: 0.1, fatG: 2, fiberG: 0 },
  { name: "Pecorino Romano (1/4 cup)", category: "Dairy", calories: 110, proteinG: 7.5, carbsG: 1, fatG: 8.5, fiberG: 0 },
  { name: "Pepperoncini (2 peppers)", category: "Vegetable", calories: 10, proteinG: 0.5, carbsG: 2, fatG: 0, fiberG: 1 },
  { name: "Pesto (1/4 cup)", category: "Condiment", calories: 290, proteinG: 5, carbsG: 4, fatG: 29, fiberG: 2 },
  { name: "Pesto Sauce (1/4 cup)", category: "Condiment", calories: 260, proteinG: 5, carbsG: 4, fatG: 26, fiberG: 2 },
  { name: "Philly Cheesesteak (6 inch)", category: "Meal/Processed", calories: 500, proteinG: 25, carbsG: 40, fatG: 28, fiberG: 3 },
  { name: "Pickle (1 spear dill)", category: "Vegetable", calories: 5, proteinG: 0.2, carbsG: 1, fatG: 0.1, fiberG: 0.3 },
  { name: "Pickle (1 whole dill)", category: "Vegetable", calories: 17, proteinG: 0.8, carbsG: 3.7, fatG: 0.2, fiberG: 1.5 },
  { name: "Pickled Cucumber (1/4 cup)", category: "Vegetable", calories: 10, proteinG: 0.5, carbsG: 2, fatG: 0, fiberG: 1 },
  { name: "Pickled Radish (1/4 cup)", category: "Vegetable", calories: 15, proteinG: 0.5, carbsG: 3, fatG: 0, fiberG: 1 },
  { name: "Pickled Turnips (2 tbsp)", category: "Vegetable", calories: 10, proteinG: 0.2, carbsG: 2, fatG: 0, fiberG: 0.5 },
  { name: "Pico de Gallo (1/4 cup)", category: "Condiment", calories: 15, proteinG: 0.5, carbsG: 3, fatG: 0, fiberG: 1 },
  { name: "Pine Nuts (1 tbsp in pesto)", category: "Nut", calories: 95, proteinG: 2, carbsG: 2, fatG: 10, fiberG: 0.5 },
  { name: "Pine Nuts (1 tbsp)", category: "Nut", calories: 95, proteinG: 2, carbsG: 2, fatG: 10, fiberG: 0.5 },
  { name: "Pine Nuts (1/2 tbsp filling)", category: "Nut", calories: 48, proteinG: 1, carbsG: 1, fatG: 5, fiberG: 0.2 },
  { name: "Pine Nuts (1/2 tbsp)", category: "Nut", calories: 48, proteinG: 1, carbsG: 1, fatG: 5, fiberG: 0.2 },
  { name: "Pisco Sour (1 drink)", category: "Beverage", calories: 250, proteinG: 1, carbsG: 25, fatG: 0, fiberG: 0 },
  { name: "Pistachio (garnish)", category: "Nut", calories: 10, proteinG: 0.4, carbsG: 0.5, fatG: 0.8, fiberG: 0.2 },
  { name: "Pistachios (1 oz shelled)", category: "Nut", calories: 159, proteinG: 5.7, carbsG: 7.7, fatG: 12.8, fiberG: 3 },
  { name: "Pita Bread (1 white)", category: "Grain", calories: 165, proteinG: 5.5, carbsG: 33, fatG: 1.2, fiberG: 1.5 },
  { name: "Pita Bread (1 whole wheat)", category: "Grain", calories: 170, proteinG: 6, carbsG: 35, fatG: 1.5, fiberG: 5 },
  { name: "Pita Bread (White 1 large)", category: "Grain", calories: 220, proteinG: 7, carbsG: 45, fatG: 2, fiberG: 2 },
  { name: "Pita Crisps (1 oz)", category: "Snack/Processed", calories: 130, proteinG: 3, carbsG: 18, fatG: 5, fiberG: 2 },
  { name: "Pizza (1 slice pepperoni)", category: "Meal/Processed", calories: 290, proteinG: 12, carbsG: 34, fatG: 12, fiberG: 2 },
  { name: "Pizza (Margherita 1 slice)", category: "Meal/Processed", calories: 250, proteinG: 12, carbsG: 30, fatG: 10, fiberG: 3 },
  { name: "Poached Egg (1 large)", category: "Protein", calories: 72, proteinG: 6.3, carbsG: 0.4, fatG: 4.8, fiberG: 0 },
  { name: "Polenta (1 cup creamy)", category: "Meal/Grain", calories: 150, proteinG: 3, carbsG: 32, fatG: 1, fiberG: 3 },
  { name: "Polenta (grilled 1 slice)", category: "Meal/Grain", calories: 120, proteinG: 2.5, carbsG: 25, fatG: 1, fiberG: 2 },
  { name: "Pomegranate Molasses (1 tsp)", category: "Condiment", calories: 15, proteinG: 0, carbsG: 4, fatG: 0, fiberG: 0 },
  { name: "Popcorn (3 cups air-popped)", category: "Grain", calories: 93, proteinG: 3, carbsG: 18.6, fatG: 1.1, fiberG: 3.6 },
  { name: "Pork Belly (1 oz in soup)", category: "Protein/Meat", calories: 145, proteinG: 3, carbsG: 0, fatG: 15, fiberG: 0 },
  { name: "Pork Bun (1 steamed)", category: "Meal/Processed", calories: 220, proteinG: 8, carbsG: 30, fatG: 8, fiberG: 2 },
  { name: "Pork Chop (4oz grilled)", category: "Protein/Meat", calories: 220, proteinG: 30, carbsG: 0, fatG: 10, fiberG: 0 },
  { name: "Pork Floss (1 tbsp)", category: "Protein/Meat", calories: 50, proteinG: 4, carbsG: 3, fatG: 2, fiberG: 0 },
  { name: "Potato (1/2 w/ pasta)", category: "Vegetable", calories: 65, proteinG: 1, carbsG: 15, fatG: 0.1, fiberG: 1 },
  { name: "Potato Chips (1 oz)", category: "Snack/Processed", calories: 160, proteinG: 2, carbsG: 15, fatG: 10, fiberG: 1 },
  { name: "Potato Leek Soup (1 cup)", category: "Meal/Vegetable", calories: 180, proteinG: 4, carbsG: 25, fatG: 7, fiberG: 3 },
  { name: "Potato Salad (1/2 cup)", category: "Meal/Vegetable", calories: 180, proteinG: 2, carbsG: 19, fatG: 11, fiberG: 2 },
  { name: "Powdered Sugar (1 tsp)", category: "Condiment", calories: 10, proteinG: 0, carbsG: 2.5, fatG: 0, fiberG: 0 },
  { name: "Pretzel Bun (1 medium)", category: "Grain", calories: 230, proteinG: 8, carbsG: 45, fatG: 2, fiberG: 2 },
  { name: "Pretzels (1 oz)", category: "Grain/Processed", calories: 110, proteinG: 3, carbsG: 23, fatG: 1, fiberG: 1 },
  { name: "Prosciutto (1 slice wrapper)", category: "Protein/Meat", calories: 35, proteinG: 4, carbsG: 0, fatG: 2.5, fiberG: 0 },
  { name: "Prosciutto (1 slice)", category: "Protein/Meat", calories: 35, proteinG: 4, carbsG: 0, fatG: 2.5, fiberG: 0 },
  { name: "Prosecco (3 oz)", category: "Beverage", calories: 70, proteinG: 0, carbsG: 2, fatG: 0, fiberG: 0 },
  { name: "Protein Bar", category: "Supplement/Processed", calories: 210, proteinG: 20, carbsG: 22, fatG: 7, fiberG: 6 },
  { name: "Protein Shake (Whey)", category: "Supplement", calories: 120, proteinG: 24, carbsG: 3, fatG: 1, fiberG: 1 },
  { name: "Provoleta (1 oz grilled cheese)", category: "Dairy", calories: 100, proteinG: 7, carbsG: 1, fatG: 8, fiberG: 0 },
  { name: "Provolone Cheese (1 slice)", category: "Dairy", calories: 100, proteinG: 7, carbsG: 1, fatG: 8, fiberG: 0 },
  { name: "Puff Pastry (1 oz wrapper)", category: "Grain", calories: 115, proteinG: 1.5, carbsG: 9, fatG: 8, fiberG: 0.5 },
  { name: "Pulled Pork Sandwich", category: "Meal/Meat", calories: 480, proteinG: 25, carbsG: 48, fatG: 20, fiberG: 3 },
  { name: "Quesadilla (Cheese 1 medium)", category: "Meal/Processed", calories: 400, proteinG: 18, carbsG: 35, fatG: 22, fiberG: 3 },
  { name: "Quinoa (1 cup cooked)", category: "Grain", calories: 222, proteinG: 8, carbsG: 39, fatG: 3.6, fiberG: 5 },
  { name: "Quinoa Salad (1 cup)", category: "Meal/Vegetarian", calories: 260, proteinG: 9, carbsG: 32, fatG: 12, fiberG: 6 },
  { name: "Ragù (filling 1 tbsp)", category: "Condiment", calories: 25, proteinG: 1.5, carbsG: 1, fatG: 1.5, fiberG: 0.5 },
  { name: "Raisins (1 tbsp)", category: "Fruit", calories: 27, proteinG: 0.3, carbsG: 7, fatG: 0, fiberG: 0.3 },
  { name: "Raisins (1/4 cup)", category: "Fruit", calories: 130, proteinG: 1.3, carbsG: 34, fatG: 0.2, fiberG: 1.6 },
  { name: "Raita (2 tbsp)", category: "Condiment/Dairy", calories: 30, proteinG: 1, carbsG: 2, fatG: 2, fiberG: 0.5 },
  { name: "Ramen (Instant 1 pack)", category: "Meal/Processed", calories: 380, proteinG: 9, carbsG: 53, fatG: 14, fiberG: 2 },
  { name: "Raspberries (1 cup)", category: "Fruit", calories: 64, proteinG: 1.5, carbsG: 14.7, fatG: 0.8, fiberG: 8 },
  { name: "Red Cabbage (1 cup raw)", category: "Vegetable", calories: 22, proteinG: 1.1, carbsG: 5.2, fatG: 0.1, fiberG: 1.6 },
  { name: "Red Onion (1/4 cup in ceviche)", category: "Vegetable", calories: 16, proteinG: 0.3, carbsG: 3.7, fatG: 0, fiberG: 0.4 },
  { name: "Red Wine (5 oz glass)", category: "Beverage", calories: 125, proteinG: 0.1, carbsG: 3.8, fatG: 0, fiberG: 0 },
  { name: "Refried Beans (1/2 cup)", category: "Legume", calories: 115, proteinG: 7, carbsG: 19, fatG: 1, fiberG: 6 },
  { name: "Reuben Sandwich", category: "Meal/Processed", calories: 650, proteinG: 28, carbsG: 35, fatG: 40, fiberG: 5 },
  { name: "Ribollita (1.5 cups soup)", category: "Meal/Soup", calories: 350, proteinG: 15, carbsG: 55, fatG: 8, fiberG: 14 },
  { name: "Rice (1/4 cup filling)", category: "Grain", calories: 51, proteinG: 1.1, carbsG: 11.1, fatG: 0.1, fiberG: 0.1 },
  { name: "Rice Krispies (1.5 cups)", category: "Grain", calories: 160, proteinG: 3, carbsG: 37, fatG: 0.5, fiberG: 0.5 },
  { name: "Ricotta (filling 1 oz)", category: "Dairy", calories: 49, proteinG: 3.2, carbsG: 0.8, fatG: 3.8, fiberG: 0 },
  { name: "Ricotta Cheese (1/4 cup)", category: "Dairy", calories: 85, proteinG: 5.5, carbsG: 2.5, fatG: 6, fiberG: 0 },
  { name: "Risotto (Mushroom 1 cup)", category: "Meal/Grain", calories: 250, proteinG: 7, carbsG: 35, fatG: 9, fiberG: 3 },
  { name: "Risotto alla Milanese (1 cup)", category: "Meal/Rice", calories: 350, proteinG: 10, carbsG: 50, fatG: 12, fiberG: 3 },
  { name: "Root Beer (1 can)", category: "Beverage", calories: 150, proteinG: 0, carbsG: 40, fatG: 0, fiberG: 0 },
  { name: "Rosemary (1 tsp topping)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.2, fatG: 0, fiberG: 0.1 },
  { name: "Rosemary (garnish)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.2, fatG: 0, fiberG: 0.1 },
  { name: "Rye Bread (1 slice)", category: "Grain", calories: 83, proteinG: 2.7, carbsG: 15.5, fatG: 1.1, fiberG: 1.9 },
  { name: "Rye Crispbread (2 slices)", category: "Grain", calories: 70, proteinG: 2, carbsG: 14, fatG: 0.5, fiberG: 3 },
  { name: "S'more (1 serving)", category: "Dessert", calories: 140, proteinG: 2, carbsG: 25, fatG: 4, fiberG: 1 },
  { name: "Saffron (pinch in risotto)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.1, fatG: 0, fiberG: 0 },
  { name: "Saffron (pinch)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.1, fatG: 0, fiberG: 0 },
  { name: "Sage (2 leaves)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.1, fatG: 0, fiberG: 0.1 },
  { name: "Sage (in beans)", category: "Condiment", calories: 1, proteinG: 0, carbsG: 0.1, fatG: 0, fiberG: 0.1 },
  { name: "Sake (3 oz)", category: "Beverage", calories: 117, proteinG: 0.4, carbsG: 3.8, fatG: 0, fiberG: 0 },
  { name: "Salami (3 slices)", category: "Protein/Processed", calories: 110, proteinG: 6, carbsG: 1, fatG: 9, fiberG: 0 },
  { name: "Salmon (4oz grilled)", category: "Protein/Fish", calories: 230, proteinG: 25, carbsG: 0, fatG: 14, fiberG: 0 },
  { name: "Salsa (1/4 cup)", category: "Vegetable", calories: 20, proteinG: 0.8, carbsG: 4.5, fatG: 0.1, fiberG: 1 },
  { name: "Salsa (2 tbsp)", category: "Condiment", calories: 10, proteinG: 0.5, carbsG: 2, fatG: 0, fiberG: 0.5 },
  { name: "Salt (1/4 tsp)", category: "Condiment", calories: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Saltimbocca (1 serving)", category: "Meal/Meat", calories: 380, proteinG: 38, carbsG: 5, fatG: 22, fiberG: 0.5 },
  { name: "Saltine Crackers (5 crackers)", category: "Grain/Processed", calories: 60, proteinG: 1, carbsG: 10, fatG: 1.5, fiberG: 0.5 },
  { name: "Samosa (1 piece vegetable)", category: "Snack/Processed", calories: 130, proteinG: 2, carbsG: 18, fatG: 6, fiberG: 2 },
  { name: "Sashimi (Salmon 3 pcs)", category: "Protein/Fish", calories: 120, proteinG: 18, carbsG: 0, fatG: 5, fiberG: 0 },
  { name: "Sauerkraut (1/2 cup)", category: "Vegetable", calories: 14, proteinG: 0.7, carbsG: 3.1, fatG: 0.1, fiberG: 2 },
  { name: "Sauerkraut (1/4 cup side)", category: "Vegetable", calories: 7, proteinG: 0.3, carbsG: 1.5, fatG: 0, fiberG: 1 },
  { name: "Sausage Link (1 cooked)", category: "Protein/Meat", calories: 85, proteinG: 5, carbsG: 1, fatG: 7, fiberG: 0 },
  { name: "Scallops (3oz seared)", category: "Protein/Seafood", calories: 95, proteinG: 17, carbsG: 5, fatG: 1, fiberG: 0 },
  { name: "Scrambled Eggs (2 large)", category: "Protein/Dairy", calories: 180, proteinG: 12, carbsG: 2, fatG: 14, fiberG: 0 },
  { name: "Sea Salt (coarse 1/4 tsp)", category: "Condiment", calories: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Seaweed Salad (1/2 cup)", category: "Vegetable", calories: 60, proteinG: 2, carbsG: 8, fatG: 3, fiberG: 2 },
  { name: "Seitan (3oz)", category: "Protein/Vegetarian", calories: 90, proteinG: 18, carbsG: 4, fatG: 1, fiberG: 1 },
  { name: "Sesame Oil (1 tsp)", category: "Condiment", calories: 40, proteinG: 0, carbsG: 0, fatG: 4.5, fiberG: 0 },
  { name: "Shawarma (Chicken 1 wrap)", category: "Meal/Processed", calories: 550, proteinG: 30, carbsG: 50, fatG: 25, fiberG: 6 },
  { name: "Shepherd's Pie (1 serving)", category: "Meal/Meat", calories: 400, proteinG: 20, carbsG: 35, fatG: 20, fiberG: 6 },
  { name: "Shish Tawook (2 skewers)", category: "Meal/Meat", calories: 300, proteinG: 35, carbsG: 5, fatG: 16, fiberG: 1 },
  { name: "Shredded Cheese (Cheddar 1/4 cup)", category: "Dairy", calories: 115, proteinG: 7, carbsG: 1, fatG: 9.5, fiberG: 0 },
  { name: "Shrimp (3oz steamed)", category: "Protein/Fish", calories: 84, proteinG: 20, carbsG: 0.2, fatG: 0.2, fiberG: 0 },
  { name: "Shrimp Cocktail (4 large shrimp)", category: "Protein/Seafood", calories: 60, proteinG: 10, carbsG: 1, fatG: 1, fiberG: 0 },
  { name: "Shrimp Scampi (1 cup)", category: "Meal/Seafood", calories: 380, proteinG: 22, carbsG: 40, fatG: 15, fiberG: 3 },
  { name: "Side Salad (light dressing)", category: "Vegetable", calories: 70, proteinG: 2, carbsG: 8, fatG: 4, fiberG: 3 },
  { name: "Silken Tofu (3oz in soup)", category: "Protein/Vegetarian", calories: 45, proteinG: 5, carbsG: 2, fatG: 2.5, fiberG: 0.5 },
  { name: "Simple Syrup (1/2 oz)", category: "Condiment", calories: 30, proteinG: 0, carbsG: 8, fatG: 0, fiberG: 0 },
  { name: "Skirt Steak (4oz grilled)", category: "Protein/Meat", calories: 240, proteinG: 26, carbsG: 0, fatG: 15, fiberG: 0 },
  { name: "Smoothie (Fruit & Yogurt)", category: "Beverage/Meal", calories: 280, proteinG: 12, carbsG: 55, fatG: 3, fiberG: 7 },
  { name: "Soda (1 can Coke)", category: "Beverage", calories: 140, proteinG: 0, carbsG: 39, fatG: 0, fiberG: 0 },
  { name: "Sour Cream (1 tbsp)", category: "Condiment/Dairy", calories: 30, proteinG: 0.4, carbsG: 0.6, fatG: 2.9, fiberG: 0 },
  { name: "Sour Cream (2 tbsp)", category: "Condiment/Dairy", calories: 60, proteinG: 0.8, carbsG: 1.3, fatG: 5.8, fiberG: 0 },
  { name: "Soy Milk (Original 1 cup)", category: "Beverage/Dairy-Alt", calories: 110, proteinG: 8, carbsG: 9, fatG: 4.5, fiberG: 2 },
  { name: "Soy Sauce (1 tbsp for dipping)", category: "Condiment", calories: 9, proteinG: 1, carbsG: 1, fatG: 0, fiberG: 0.1 },
  { name: "Soy Sauce (1 tbsp in stir-fry)", category: "Condiment", calories: 9, proteinG: 1, carbsG: 1, fatG: 0, fiberG: 0.1 },
  { name: "Soyrizo (2 oz)", category: "Protein/Vegetarian", calories: 140, proteinG: 10, carbsG: 6, fatG: 9, fiberG: 3 },
  { name: "Spaghetti (side)", category: "Grain", calories: 100, proteinG: 3.5, carbsG: 21, fatG: 0.5, fiberG: 1 },
  { name: "Spaghetti Bolognese", category: "Meal/Pasta", calories: 460, proteinG: 20, carbsG: 55, fatG: 18, fiberG: 6 },
  { name: "Spicy Mustard (1 tbsp)", category: "Condiment", calories: 10, proteinG: 0.5, carbsG: 1, fatG: 0.5, fiberG: 0.5 },
  { name: "Spinach (1 cup, raw)", category: "Vegetable", calories: 7, proteinG: 0.9, carbsG: 1.1, fatG: 0.1, fiberG: 0.7 },
  { name: "Spinach Artichoke Dip (1/4 cup)", category: "Snack/Processed", calories: 160, proteinG: 5, carbsG: 6, fatG: 14, fiberG: 2 },
  { name: "Split Pea Soup (1 cup)", category: "Meal/Legume", calories: 180, proteinG: 11, carbsG: 30, fatG: 2, fiberG: 10 },
  { name: "Spring Roll (Veg 2 rolls)", category: "Snack/Processed", calories: 180, proteinG: 4, carbsG: 25, fatG: 7, fiberG: 3 },
  { name: "Sriracha (1 tsp)", category: "Condiment", calories: 5, proteinG: 0.1, carbsG: 1, fatG: 0.1, fiberG: 0.1 },
  { name: "Stale Bread (1/2 cup in soup)", category: "Grain", calories: 80, proteinG: 3, carbsG: 15, fatG: 1, fiberG: 1 },
  { name: "Steamed Broccoli (1 cup)", category: "Vegetable", calories: 55, proteinG: 3.7, carbsG: 11.2, fatG: 0.6, fiberG: 5.1 },
  { name: "String Cheese (1 stick)", category: "Dairy", calories: 80, proteinG: 6, carbsG: 1, fatG: 6, fiberG: 0 },
  { name: "Stuffed Grape Leaves (3 pcs)", category: "Meal/Vegetarian", calories: 150, proteinG: 3, carbsG: 20, fatG: 7, fiberG: 3 },
  { name: "Sugar (1 tsp for cereal)", category: "Condiment", calories: 16, proteinG: 0, carbsG: 4, fatG: 0, fiberG: 0 },
  { name: "Sugar (1 tsp, in broth)", category: "Condiment", calories: 16, proteinG: 0, carbsG: 4, fatG: 0, fiberG: 0 },
  { name: "Sumac (1/2 tsp dressing)", category: "Condiment", calories: 5, proteinG: 0.1, carbsG: 1, fatG: 0.2, fiberG: 0.5 },
  { name: "Supplì (1 piece fried rice ball)", category: "Snack/Processed", calories: 200, proteinG: 8, carbsG: 25, fatG: 8, fiberG: 2 },
  { name: "Sweet & Sour Chicken (1 cup)", category: "Meal/Processed", calories: 380, proteinG: 18, carbsG: 45, fatG: 15, fiberG: 3 },
  { name: "Sweet Chili Sauce (2 tbsp)", category: "Condiment", calories: 70, proteinG: 0, carbsG: 17, fatG: 0, fiberG: 0.5 },
  { name: "Sweet Potato (1 medium baked)", category: "Vegetable", calories: 103, proteinG: 2.3, carbsG: 23.6, fatG: 0.2, fiberG: 3.8 },
  { name: "Sweet Tea (16 oz)", category: "Beverage", calories: 180, proteinG: 0, carbsG: 46, fatG: 0, fiberG: 0 },
  { name: "Sweet Vermouth (1 oz)", category: "Beverage", calories: 40, proteinG: 0, carbsG: 5, fatG: 0, fiberG: 0 },
  { name: "Swiss Cheese (1 slice)", category: "Dairy", calories: 106, proteinG: 7.6, carbsG: 1, fatG: 8, fiberG: 0 },
  { name: "T-Bone Steak (6oz)", category: "Protein/Meat", calories: 460, proteinG: 38, carbsG: 0, fatG: 33, fiberG: 0 },
  { name: "Tabouli (1/2 cup)", category: "Meal/Vegetarian", calories: 120, proteinG: 3, carbsG: 15, fatG: 6, fiberG: 4 },
  { name: "Tagliatelle al Ragù (Bolognese)", category: "Meal/Pasta", calories: 550, proteinG: 28, carbsG: 65, fatG: 20, fiberG: 7 },
  { name: "Tahini (1 tbsp)", category: "Condiment", calories: 89, proteinG: 2.6, carbsG: 3.2, fatG: 8, fiberG: 1.4 },
  { name: "Tahini Sauce (1 tbsp)", category: "Condiment", calories: 30, proteinG: 1, carbsG: 1.5, fatG: 2.5, fiberG: 0.5 },
  { name: "Tamarind Chutney (1 tbsp)", category: "Condiment", calories: 20, proteinG: 0.1, carbsG: 5, fatG: 0, fiberG: 0.5 },
  { name: "Tapioca Pearls (1/4 cup boba)", category: "Condiment", calories: 100, proteinG: 0, carbsG: 25, fatG: 0, fiberG: 0 },
  { name: "Tartar Sauce (2 tbsp)", category: "Condiment", calories: 60, proteinG: 0.2, carbsG: 2, fatG: 5.5, fiberG: 0.1 },
  { name: "Tea (Green, 1 cup)", category: "Beverage", calories: 2, proteinG: 0.5, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Tempeh (3oz)", category: "Protein/Vegetarian", calories: 160, proteinG: 16, carbsG: 8, fatG: 9, fiberG: 5 },
  { name: "Thai Basil (garnish)", category: "Condiment", calories: 1, proteinG: 0.1, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Thai Iced Tea (1 glass)", category: "Beverage", calories: 250, proteinG: 3, carbsG: 35, fatG: 12, fiberG: 0 },
  { name: "Tilapia (4oz baked)", category: "Protein/Fish", calories: 110, proteinG: 22, carbsG: 0, fatG: 2.5, fiberG: 0 },
  { name: "Tiramisu (1 slice)", category: "Dessert", calories: 450, proteinG: 7, carbsG: 42, fatG: 28, fiberG: 2 },
  { name: "Tofu (4oz firm)", category: "Protein/Vegetarian", calories: 90, proteinG: 10, carbsG: 3, fatG: 5, fiberG: 2 },
  { name: "Tofu Scramble", category: "Meal/Vegetarian", calories: 250, proteinG: 20, carbsG: 8, fatG: 16, fiberG: 4 },
  { name: "Tofu Stir-fry", category: "Meal/Vegetarian", calories: 400, proteinG: 18, carbsG: 30, fatG: 22, fiberG: 7 },
  { name: "Tomato (1 medium sliced)", category: "Vegetable", calories: 22, proteinG: 1.1, carbsG: 4.8, fatG: 0.2, fiberG: 1.5 },
  { name: "Tomato (1/4 cup side)", category: "Vegetable", calories: 8, proteinG: 0.3, carbsG: 1.8, fatG: 0.1, fiberG: 0.5 },
  { name: "Tomato Sauce (1/2 cup)", category: "Condiment", calories: 40, proteinG: 1.5, carbsG: 7, fatG: 1, fiberG: 2 },
  { name: "Tomato Soup (1 can)", category: "Meal/Vegetable", calories: 170, proteinG: 4, carbsG: 25, fatG: 6, fiberG: 4 },
  { name: "Tortilla Chips (1 oz)", category: "Snack/Processed", calories: 140, proteinG: 2, carbsG: 19, fatG: 7, fiberG: 2 },
  { name: "Trail Mix (1/4 cup)", category: "Snack/Processed", calories: 190, proteinG: 5, carbsG: 20, fatG: 12, fiberG: 3 },
  { name: "Trofie Pasta (1 cup cooked)", category: "Grain", calories: 210, proteinG: 7, carbsG: 43, fatG: 1, fiberG: 2 },
  { name: "Tuna (Canned 3oz in water)", category: "Protein/Fish", calories: 90, proteinG: 20, carbsG: 0, fatG: 1, fiberG: 0 },
  { name: "Tuna Melt", category: "Meal/Processed", calories: 450, proteinG: 25, carbsG: 32, fatG: 25, fiberG: 3 },
  { name: "Tuna Salad (1/2 cup)", category: "Meal/Fish", calories: 190, proteinG: 19, carbsG: 2, fatG: 12, fiberG: 1 },
  { name: "Tuna Sauce (2 tbsp)", category: "Condiment", calories: 100, proteinG: 4, carbsG: 1, fatG: 9, fiberG: 0 },
  { name: "Turkey Bacon (2 slices)", category: "Protein/Meat", calories: 70, proteinG: 6, carbsG: 1, fatG: 5, fiberG: 0 },
  { name: "Turkey Burger (1 patty)", category: "Protein/Meat", calories: 160, proteinG: 22, carbsG: 2, fatG: 8, fiberG: 0 },
  { name: "Turkey Chili (1 cup)", category: "Meal/Meat", calories: 250, proteinG: 22, carbsG: 25, fatG: 7, fiberG: 8 },
  { name: "Turkey Sandwich (on wheat)", category: "Meal/Processed", calories: 340, proteinG: 22, carbsG: 34, fatG: 12, fiberG: 5 },
  { name: "Turkey Sausage (1 patty)", category: "Protein/Meat", calories: 70, proteinG: 9, carbsG: 1, fatG: 4, fiberG: 0 },
  { name: "Turkish Coffee (1 small cup)", category: "Beverage", calories: 5, proteinG: 0.2, carbsG: 0.5, fatG: 0, fiberG: 0 },
  { name: "Turmeric (1 tsp)", category: "Condiment", calories: 9, proteinG: 0.3, carbsG: 1.9, fatG: 0.1, fiberG: 0.7 },
  { name: "Tzatziki Sauce (2 tbsp)", category: "Condiment/Dairy", calories: 30, proteinG: 1.5, carbsG: 2, fatG: 2, fiberG: 0 },
  { name: "Veal Parmesan (1 serving)", category: "Meal/Meat", calories: 550, proteinG: 40, carbsG: 30, fatG: 30, fiberG: 4 },
  { name: "Vegetable Broth (1 cup)", category: "Beverage", calories: 15, proteinG: 1, carbsG: 3, fatG: 0, fiberG: 1 },
  { name: "Vegetable Soup (1 can)", category: "Meal/Vegetable", calories: 140, proteinG: 4, carbsG: 22, fatG: 4, fiberG: 6 },
  { name: "Veggie Burger (1 patty)", category: "Protein/Vegetarian", calories: 120, proteinG: 11, carbsG: 10, fatG: 4, fiberG: 5 },
  { name: "Veggie Straws (1 oz)", category: "Snack/Processed", calories: 130, proteinG: 1, carbsG: 17, fatG: 7, fiberG: 1 },
  { name: "Vitello Tonnato (1 serving)", category: "Meal/Meat", calories: 380, proteinG: 35, carbsG: 3, fatG: 25, fiberG: 0.5 },
  { name: "Vodka (1.5 oz)", category: "Beverage", calories: 97, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Vodka Soda (1 drink)", category: "Beverage", calories: 100, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 },
  { name: "Waffle Cone (1 small)", category: "Grain", calories: 70, proteinG: 1, carbsG: 13, fatG: 1.5, fiberG: 0.5 },
  { name: "Waffles (2 homemade)", category: "Grain", calories: 220, proteinG: 6, carbsG: 28, fatG: 9, fiberG: 1.5 },
  { name: "Walnuts (1 tbsp chopped)", category: "Nut", calories: 46, proteinG: 1.1, carbsG: 1, fatG: 4.6, fiberG: 0.5 },
  { name: "Wasabi (1 tsp)", category: "Condiment", calories: 10, proteinG: 0.1, carbsG: 2.2, fatG: 0.1, fiberG: 0.3 },
  { name: "Water Cracker (5 crackers)", category: "Grain/Processed", calories: 70, proteinG: 1.5, carbsG: 12, fatG: 1.5, fiberG: 0.5 },
  { name: "Watermelon (1 cup diced)", category: "Fruit", calories: 46, proteinG: 0.9, carbsG: 11.5, fatG: 0.2, fiberG: 0.6 },
  { name: "Whiskey (1.5 oz shot)", category: "Beverage", calories: 105, proteinG: 0, carbsG: 0.1, fatG: 0, fiberG: 0 },
  { name: "White Beans (Tuscan style 1/2 cup)", category: "Legume", calories: 150, proteinG: 8, carbsG: 20, fatG: 4, fiberG: 7 },
  { name: "White Bread (1 slice)", category: "Grain", calories: 70, proteinG: 2, carbsG: 13, fatG: 1, fiberG: 0.6 },
  { name: "White Rice (1 cup cooked)", category: "Grain", calories: 204, proteinG: 4.2, carbsG: 44.5, fatG: 0.4, fiberG: 0.6 },
  { name: "White Wine (5 oz glass)", category: "Beverage", calories: 121, proteinG: 0.1, carbsG: 3.8, fatG: 0, fiberG: 0 },
  { name: "White Wine Sauce (1/4 cup)", category: "Condiment", calories: 80, proteinG: 1, carbsG: 4, fatG: 6, fiberG: 0.5 },
  { name: "Whole Wheat Toast (1 slice)", category: "Grain", calories: 80, proteinG: 4, carbsG: 14, fatG: 1, fiberG: 2 },
  { name: "Wild Rice (1 cup cooked)", category: "Grain", calories: 166, proteinG: 6.5, carbsG: 35, fatG: 0.6, fiberG: 3 },
  { name: "Yellow Rice (1 cup)", category: "Grain", calories: 230, proteinG: 4, carbsG: 50, fatG: 1, fiberG: 2 },
  { name: "Za'atar (1 tbsp)", category: "Condiment", calories: 40, proteinG: 1, carbsG: 3, fatG: 3, fiberG: 1.5 },
]
